/**
 * @fileoverview Server-local catalog record for cyanheads-mcp-server itself.
 * The remote fleet.json is generated by the portfolio from live `GET /mcp` +
 * `tools/list` sweeps of the fleet and does not include the discovery front
 * door, so the front door cannot describe itself from the remote catalog alone.
 * This module supplies a static record that CatalogService consults only after
 * a remote-catalog lookup misses.
 * @module services/catalog/self-record
 */

import { readFileSync } from 'node:fs';
import { describeEntryTool } from '@/mcp-server/tools/definitions/describe-entry.tool.js';
import { searchCatalogTool } from '@/mcp-server/tools/definitions/search-catalog.tool.js';
import type { CatalogRecord, CatalogTool } from './types.js';

/** Catalog name this server is addressable by — the repo/package basename. */
export const SELF_RECORD_NAME = 'cyanheads-mcp-server';

/** Hosted Streamable HTTP endpoint for the discovery front door. */
const SELF_RECORD_ENDPOINT = 'https://cyanheads.caseyjhand.com/mcp';

interface SelfPackageInfo {
  description: string;
  version: string;
}

/**
 * Read `version` and `description` from this package's own package.json rather
 * than restating them, so a release bump can never leave the self-record stale.
 * Resolved relative to this module rather than `process.cwd()` so it holds under
 * `npx`, Docker, and the test runner alike — `src/services/catalog/` and
 * `dist/services/catalog/` sit at the same depth below the package root, and npm
 * ships package.json in every published tarball.
 */
function readSelfPackage(): SelfPackageInfo {
  const raw = readFileSync(new URL('../../../package.json', import.meta.url), 'utf-8');
  const parsed = JSON.parse(raw) as { description?: string; version?: string };
  if (!parsed.version || !parsed.description) {
    throw new Error('package.json is missing "version" or "description" for the self record');
  }
  return { description: parsed.description, version: parsed.version };
}

/**
 * Derive the tool list from the registered tool definitions so the self record
 * always names the tools this build actually advertises in `tools/list`.
 *
 * `embedding: []` is deliberate and safe. The vector index is built solely from
 * `FleetPayload.servers` in `CatalogService._buildIndex`, which sizes its packed
 * Float32Arrays from that payload and dimension-checks every vector it packs.
 * This record is never a member of that payload — it is consulted only after an
 * exact-name miss in `getServer()` / `getTool()` — so its embedding is never
 * packed, never dot-producted, and never dimension-checked. The tradeoff is that
 * `cyanheads_search_catalog` will not surface this server as a semantic match;
 * only exact-name resolution reaches it.
 */
function selfTools(): CatalogTool[] {
  return [searchCatalogTool, describeEntryTool].map((definition) => ({
    name: definition.name,
    description: definition.description,
    embedding: [],
  }));
}

let _record: CatalogRecord | undefined;

/**
 * The static catalog record describing this server. Built on first use and
 * memoized, so the package.json read costs nothing for a process that never
 * resolves this name.
 */
export function getSelfCatalogRecord(): CatalogRecord {
  if (_record) return _record;

  const pkg = readSelfPackage();
  _record = {
    name: SELF_RECORD_NAME,
    // Display identity across this fleet is the hyphenated repo name, not a Title Case label.
    displayName: SELF_RECORD_NAME,
    description: pkg.description,
    category: 'utility',
    endpoint: SELF_RECORD_ENDPOINT,
    npm: '@cyanheads/cyanheads-mcp-server',
    github: 'https://github.com/cyanheads/cyanheads-mcp-server',
    version: pkg.version,
    auth: 'none',
    embedding: [],
    tools: selfTools(),
  };
  return _record;
}

/**
 * Look up one of this server's own tools by name. Returns null for any other
 * name, leaving the caller's not-found path intact.
 */
export function getSelfCatalogTool(
  name: string,
): (CatalogTool & { serverRecord: CatalogRecord }) | null {
  const record = getSelfCatalogRecord();
  const tool = record.tools.find((t) => t.name === name);
  return tool ? { ...tool, serverRecord: record } : null;
}
